### DISCUSSION TITLE
Docker and additional languages

### DISCUSSION THREAD

**Discussion by globalexport** [microsoft/presidio#1308] [Q&A] [answered]
Hi! 
I am trying to add additional languages to the Docker setup. I added 
```
nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
  -
    lang_code: de
    model_name: de_core_news_md
``` 
German to the `config/default.yaml` and ran:
`docker-compose -f docker-compose-text.yml up --build -d`  

But I am still getting 
```
{
  "error": "No matching recognizers were found to serve the request."
}
```
I then tried to download the model within the container with
`pipenv run python -m spacy download de_core_news_md` 
and
`pipenv run python install_nlp_models.py`

but to no avail. 

What do I need to do to get a second language working? 
Thank you!
