### DISCUSSION TITLE
Troubleshooting EsNifRecognizer in a Docker Container supporting Spanish and Catalan

### DISCUSSION THREAD

**Discussion by DipuAlba1** [microsoft/presidio#1533] [Q&A] [answered]
Hi, we are trying to create a Docker container that supports Spanish and Catalan. The Dockerfile is as follows:

```
FROM mcr.microsoft.com/presidio-analyzer:latest

USER root

RUN pip install --no-cache-dir spacy
RUN python -m spacy download en_core_web_lg
RUN python -m spacy download es_core_news_lg
RUN python -m spacy download ca_core_news_lg

COPY default.yaml /usr/bin/presidio-analyzer/presidio_analyzer/conf/default.yaml
COPY default_recognizers.yaml /usr/bin/presidio-analyzer/presidio_analyzer/conf/default_recognizers.yaml
```

Here is the default.yaml:

```
nlp_engine_name: spacy
models:
  - lang_code: es
    model_name: es_core_news_lg
  - lang_code: ca
    model_name: ca_core_news_lg

ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION

  low_confidence_score_multiplier: 0.4
  labels_to_ignore:
    - ORGANIZATION
    - CARDINAL
    - EVENT
    - LANGUAGE
    - LAW
    - MONEY
    - ORDINAL
    - PERCENT
    - PRODUCT
    - QUANTITY
    - WORK_OF_ART
    - DATE_TIME
```

However, we can't get the `EsNifRecognizer` to work. The logs show the following warning message:

```
2025-02-27 08:17:14,753 - presidio-analyzer - WARNING - Recognizer not added to registry because language is not supported by registry - EsNifRecognizer supported languages: es, registry supported languages: en
2025-02-27 08:17:14,753 - presidio-analyzer - WARNING - Recognizer not added to registry because language is not supported by registry - EsNieRecognizer supported languages: es, registry supported languages: en
```

Example request:

```
{
    "text": "Perico de los Palotes García, con DNI 12345678Z y con domicilio en Albacete. Expone lo siguiente.",
    //"entities": ["ES_NIF"],
    //"entities": ["EsNifRecognizer"],
    "language": "es"
}
```

Response:

```
[
    {
        "analysis_explanation": null,
        "end": 28,
        "entity_type": "PERSON",
        "recognition_metadata": {
            "recognizer_identifier": "SpacyRecognizer_140505351196192",
            "recognizer_name": "SpacyRecognizer"
        },
        "score": 0.85,
        "start": 0
    },
    {
        "analysis_explanation": null,
        "end": 75,
        "entity_type": "LOCATION",
        "recognition_metadata": {
            "recognizer_identifier": "SpacyRecognizer_140505351196192",
            "recognizer_name": "SpacyRecognizer"
        },
        "score": 0.85,
        "start": 67
    }
]
```

But it doesn't detect the 12345678Z NIF number.

We attempted to modify the `default_recognizers.yaml` file, but if we do so, the service fails to start and shows an error indicating that the worker failed to boot.
```
supported_languages:
  - es
  - ca
global_regex_flags: 26

recognizers:
  - name: CreditCardRecognizer
    supported_languages:
    - language: es
      context: [tarjeta, credito, visa, mastercard, cc, amex, discover, jcb, diners, maestro, instapayment]
    - language: ca
      context: [tarjeta, credito, visa, mastercard, cc, amex, discover, jcb, diners, maestro, instapayment]
    type: predefined

  - name: EsNifRecognizer
    supported_languages:
    - es
    type: predefined

  - name: EsNieRecognizer
    supported_languages:
    - es
    type: predefined

... rest of recognizers ...

```

docker logs:

```
2025-02-27 08:27:35,097 - presidio-analyzer - INFO - Loaded recognizer: SpacyRecognizer
[2025-02-27 08:27:39 +0000] [6] [ERROR] Worker (pid:11) exited with code 3
[2025-02-27 08:27:39 +0000] [6] [ERROR] Shutting down: Master
[2025-02-27 08:27:39 +0000] [6] [ERROR] Reason: Worker failed to boot.
```

How can we create a Docker container that supports Spanish, Catalan, and also uses the EsNifRecognizer without running into these issues?

**Comment by omri374** [comment]
We'll look into this. From a first glance it looks like the recognizers aren't loaded correctly. Have you tried the same configuration outside the Docker in Python by any chance? using the `AnalyzerEngineProvider`? https://microsoft.github.io/presidio/analyzer/analyzer_engine_provider/

**Comment by DipuAlba1** [comment]
No, we haven't tried because we are not interested in making it work outside of Docker, as our .NET platform does not use Python. We have tried numerous configurations and reviewed the documentation to get the container working with English, Spanish, and Catalan, but the EsNifRecognizer never works. We simply need a container that can support Spanish and Catalan but also have the EsNifRecognizer working. Any ideas or example? Why the "language is not supported by registry"?

**Comment by omri374** [comment]
Please try the following conf file and let me know if it works.

```yaml
supported_languages:
  - es
  - ca
default_score_threshold: 0.4


recognizer_registry:
  supported_languages:
    - es
    - ca
  global_regex_flags: 26
  recognizers:
    - name: CreditCardRecognizer
      supported_languages:
      - language: es
        context: [tarjeta, credito, visa, mastercard, cc, amex, discover, jcb, diners, maestro, instapayment]
      - language: ca
        context: [tarjeta, credito, visa, mastercard, cc, amex, discover, jcb, diners, maestro, instapayment]
      type: predefined

    - name: EsNifRecognizer
      supported_languages:
      - es
      type: predefined

    - name: EsNieRecognizer
      supported_languages:
      - es
      type: predefined

nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: es
      model_name: es_core_news_lg
    - lang_code: ca
      model_name: ca_core_news_lg

  ner_model_configuration:
    model_to_presidio_entity_mapping:
      PER: PERSON
      PERSON: PERSON
      NORP: NRP
      FAC: LOCATION
      LOC: LOCATION
      GPE: LOCATION
      LOCATION: LOCATION
      ORG: ORGANIZATION
      ORGANIZATION: ORGANIZATION

    low_confidence_score_multiplier: 0.4
    labels_to_ignore:
      - ORGANIZATION
      - CARDINAL
      - EVENT
      - LANGUAGE
      - LAW
      - MONEY
      - ORDINAL
      - PERCENT
      - PRODUCT
      - QUANTITY
      - WORK_OF_ART
      - DATE_TIME
```

It includes all the configuration, so you can only pass the `ANALYZER_CONF_FILE` parameter, ignoring the others.

What's likely happening is that the conf file loading failed for some reason, and it reverted to the default. The logger is logging a warning in this case, but the logs aren't exposed to the user. (This is my assumption).


Please try it it out and let me know if it works.

**Reply by omri374** [reply]
This is what I got (not in the Docker version, but directly in Flask, but it should be identical):

```json
[
  {
    "analysis_explanation": null,
    "end": 47,
    "entity_type": "ES_NIF",
    "recognition_metadata": {
      "recognizer_identifier": "EsNifRecognizer_13808910288",
      "recognizer_name": "EsNifRecognizer"
    },
    "score": 1,
    "start": 38
  },
  {
    "analysis_explanation": null,
    "end": 28,
    "entity_type": "PERSON",
    "recognition_metadata": {
      "recognizer_identifier": "SpacyRecognizer_13808909952",
      "recognizer_name": "SpacyRecognizer"
    },
    "score": 0.85,
    "start": 0
  },
  {
    "analysis_explanation": null,
    "end": 75,
    "entity_type": "LOCATION",
    "recognition_metadata": {
      "recognizer_identifier": "SpacyRecognizer_13808909952",
      "recognizer_name": "SpacyRecognizer"
    },
    "score": 0.85,
    "start": 67
  }
]
```

**Comment by rasputino** [comment, marked as answer]
After much struggling with the configuration files, with the help of an AI I was able to obtain this error from `poetry gunicorn`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/bin/presidio-analyzer/app.py", line 139, in create_app
    server = Server()
  File "/usr/bin/presidio-analyzer/app.py", line 44, in __init__
    self.engine: AnalyzerEngine = AnalyzerEngineProvider(
  File "/usr/bin/presidio-analyzer/presidio_analyzer/analyzer_engine_provider.py", line 83, in create_engine
    analyzer = AnalyzerEngine(
  File "/usr/bin/presidio-analyzer/presidio_analyzer/analyzer_engine.py", line 87, in __init__
    raise ValueError(
ValueError: Misconfigured engine, supported languages have to be consistentregistry.supported_languages: ['en', 'es', 'ca'], analyzer_engine.supported_languages: ['en']
```

And thanks to this, I learned that we also needed to modify the `default_analyzer.yaml` file.

**Reply by Rinaldi-Simone** [reply]
Hi, I’m currently facing an issue similar to the one you described.

You mentioned that modifying the default_analyzer.yaml file was necessary to fix it, but didn’t specify exactly what needed to be changed.

In my case, I’m trying to add support for two languages: en and it. I updated my default_analyzer.yaml as follows:

```
supported_languages: 
  - language: en
  - language: it
default_score_threshold: 0
```

And this is my default.yaml file:

```
nlp_engine_name: spacy

models:
  - lang_code: en
    model_name: en_core_web_lg
  - lang_code: it
    model_name: it_core_news_lg

ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME

  low_confidence_score_multiplier: 0.4

  low_score_entity_names: []

  labels_to_ignore:
    - ORGANIZATION
    - CARDINAL
    - EVENT
    - LANGUAGE
    - LAW
    - MONEY
    - ORDINAL
    - PERCENT
    - PRODUCT
    - QUANTITY
    - WORK_OF_ART
```

Despite this, I still encounter the following error when starting the Docker container:

```
[2025-07-07 11:17:28 +0000] [6] [ERROR] Worker (pid:12) exited with code 3  
[2025-07-07 11:17:28 +0000] [6] [ERROR] Shutting down: Master  
[2025-07-07 11:17:28 +0000] [6] [ERROR] Reason: Worker failed to boot.
```

Could you please clarify what changes are required to make the multi-language setup work properly?

Thanks in advance for your help!

**Reply by omri374** [reply]
Seems like the server crashes on startup. Is this happening with the default config too? Have you tried running this outside docker and without gunicorn? If possible, try to extract more logs to understand what's failing.

**Reply by rasputino** [reply]
The files:

```
# cat default_analyzer.yaml
supported_languages:
  - en
  - es
  - ca
default_score_threshold: 0


# cat default.yaml
nlp_engine_name: spacy
models:
  - lang_code: en
    model_name: en_core_web_md
  - lang_code: es
    model_name: es_core_news_md
  - lang_code: ca
    model_name: ca_core_news_md

ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION

  low_confidence_score_multiplier: 0.4
  labels_to_ignore:
    - ORGANIZATION
    - CARDINAL
    - EVENT
    - LANGUAGE
    - LAW
    - MONEY
    - ORDINAL
    - PERCENT
    - PRODUCT
    - QUANTITY
    - WORK_OF_ART
    - DATE_TIME

# cat default_recognizers.yaml
supported_languages:
  - en
  - es
  - ca
global_regex_flags: 26

recognizers:
  # Recognizers listed here can either be loaded from the recognizers defined in code (type: predefined),
  # or created based on the provided configuration (type: custom).
  # For predefined:
  # - If only a recognizer name is provided, a predefined recognizer with this name and default parameters will be loaded.
  # - If a parameter isn't provided, the default one would be loaded.
  # For custom:
  # - See an example configuration here: https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/conf/example_recognizers.yaml
  # - Custom pattern recognizers with this configuration can be added to this file, with type: custom
  #  For recognizers supporting more than one language, an instance of the recognizer for each language will be created.
  # For example, see the CreditCardRecognizer definition below:
  - name: CreditCardRecognizer
    supported_languages:
    - language: en
    - language: es
    type: predefined

  - name: EsNifRecognizer
    supported_languages:
    - es
    type: predefined

  - name: EsNieRecognizer
    supported_languages:
    - es
    type: predefined

  - name: CryptoRecognizer
    type: predefined

  - name: EmailRecognizer
    type: predefined

  - name: IbanRecognizer
    type: predefined

  - name: IpRecognizer
    type: predefined

  - name: PhoneRecognizer
    type: predefined

  - name: UrlRecognizer
    type: predefined
```
