### ISSUE TITLE
Add keep operator as deanonymizer too

### ISSUE THREAD

**Issue by dinigo** [microsoft/presidio#1254]
My use-case anonymises some data with encryption, and some other with destructive methods (replace, mask).

Then I run de de-anonymisation against all of those cases. Some (`MESSAGE_ID`) need to be decrypted, and some others (`CUSTOM_ID` or even `CUSTOM_DATE` which wasn't obfuscated) need to pass through.

```yaml
analyzer_config:
    entities: [ CUSTOM_ID, MESSAGE_ID, UUID, CUSTOM_DATE ]
    language: en
anonymize_config:
    # if not provided, replace replaces the value with the info_type, <CUSTOM_ID>
    CUSTOM_ID:
        type: replace
    UUID:
        type: kms_encrypt
        key_version_name: projects/my-secret-project/locations/europe-west2/keyRings/dlp/cryptoKeys/presidio-aes-key
    MESSAGE_ID:
        type: kms_encrypt
        key_version_name: projects/my-secret-project/locations/europe-west2/keyRings/dlp/cryptoKeys/presidio-aes-key
    # the rest of the detected fields (CUSTOM_DATE*) will be kept as they are
    DEFAULT:
        type: keep
deanonymize_config:
    # see here we use the `kms_decrypt` operator instead of the `kms_encrypt`
    UUID:
        type: kms_decrypt
        key_version_name: projects/my-secret-project/locations/europe-west2/keyRings/dlp/cryptoKeys/presidio-aes-key
    MESSAGE_ID:
        type: kms_decrypt
        key_version_name: projects/my-secret-project/locations/europe-west2/keyRings/dlp/cryptoKeys/presidio-aes-key
    DEFAULT:
        type: keep
```

However, as `keep` is only registered as anonymiser, I cannot use it. I just copy pasted it to be able to implement the usecase above.

I think this change/fixx might belong to the core, since the use-case of anonymising several and then retrieving only encrypted is a common one.
