### ISSUE TITLE
Why does Presidio spin up so many threads?

### ISSUE THREAD

**Issue by ilyakamens** [microsoft/presidio#1302]
I'm using Presidio with Flask and Gunicorn in Docker locally (via Docker Compose). When I get a shell in my container and view the process list, I see 12 threads. Can I configure Presidio to use fewer threads? Out of curiosity, why does it need so many threads? Also, is it possible for me to lower its memory footprint?

<img width="750" alt="image" src="https://github.com/microsoft/presidio/assets/3293811/d423d5fa-1875-46dd-87dd-0f8601d1a012">

Compose configuration:

```yaml
fcnlp:
  container_name: fcnlp
  build: .
  image: freshcard-server:dev
  command: gunicorn nlp.app:app -c /app/scripts/conf/gunicorn.conf-nlp.py --reload
  restart: on-failure
  volumes:
    - .:/app
```

Gunicorn configuration:

```python
import os

workers = int(os.environ.get("NLP_GUNICORN_PROCS", "1"))
bind = "0.0.0.0:%s" % os.environ.get("NLP_FLASK_PORT", "5000")
proc_name = "gunicorn"
pidfile = "/var/run/gunicorn.pid"
accesslog = "/dev/null"
errorlog = "-"
worker_class = "gthread"
debug = True
timeout = 600
```

Python version:
```
python:3.10.10-slim-bullseye
```

Requirements (among others):
```
Flask==1.1.1
gunicorn==21.2.0
presidio-analyzer==2.2.351
presidio-anonymizer==2.2.351
```

Thanks!
