### ISSUE TITLE
Add support for Gliner in Docker image

### ISSUE THREAD

**Issue by btiernay** [microsoft/presidio#1525]
**Is your feature request related to a problem? Please describe.**
Currently trying to use the `GLiNERRecognizer` in the Docker image by overriding the configuration does not work:
```yaml
- name: GLiNERRecognizer
  type: predefined
  supported_languages:
  - en
  supported_entities:
  - PERSON
  - EMAIL
  - PHONE_NUMBER
  model_to_presidio_entity_mapping:
    PERSON: PERSON
    EMAIL: EMAIL
    PHONE: PHONE_NUMBER
  low_score_entity_names:
  - PERSON
  - EMAIL
  - PHONE_NUMBER
  labels_to_ignore: []
  model_name: "urchade/gliner_multi_pii-v1"
  threshold: 0.30
```

When instrumenting logging in `gliner_recognizer.py`:
```
import traceback

from presidio_analyzer import (
    AnalysisExplanation,
    LocalRecognizer,
    RecognizerResult,
)
from presidio_analyzer.nlp_engine import NerModelConfiguration, NlpArtifacts

logger = logging.getLogger("presidio-analyzer")

try:
    from gliner import GLiNER, GLiNERConfig
    logger.info("GLiNER import successful")
except ImportError as e:
    GLiNER = None
    GLiNERConfig = None
    logger.error("Failed to import GLiNER: %s", str(e))
    logger.error("Traceback: %s", traceback.format_exc())
```

We get the following error (which would otherwise silently fail):
```
presidio-analyzer-1  | Failed to import GLiNER: No module named 'gliner'
presidio-analyzer-1  | Traceback: Traceback (most recent call last):
presidio-analyzer-1  |   File "/usr/bin/presidio-analyzer/presidio_analyzer/predefined_recognizers/gliner_recognizer.py", line 16, in <module>
presidio-analyzer-1  |     from gliner import GLiNER, GLiNERConfig
presidio-analyzer-1  | ModuleNotFoundError: No module named 'gliner'
```

**Describe the solution you'd like**
Have a build that includes support for GLiNER and GLiNERRecognizer. Failing that, having instructions on how to easily add it post facto would be greatly appreciated.

**Describe alternatives you've considered**
Tried to exec into the container and run `poetry install --no-root -E gliner` but that didn't work.

**Additional context**
