### ISSUE TITLE
AKS: Internal Load Balancer setup? 

### ISSUE THREAD

**Issue by fd98279** [microsoft/presidio#371]
**Describe the bug**
How to set up AKS internal load balancer to the api PODs?

**To Reproduce**
Set up the LB like this:
1) YAML file
```yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: presidio-demo-presidio-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

2) Applied the YAML file:
```bash
$ kubectl apply -f internal-lb.yml
service/internal-app created
```

3) Service is up:
```bash
$ kubectl get service internal-app
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
internal-app   LoadBalancer   10.0.172.196   10.240.0.7    80:30953/TCP   81s

$ kubectl describe service internal-app
Name:                     internal-app
Namespace:                default
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:                 app=presidio-demo-presidio-api
Type:                     LoadBalancer
IP:                       10.0.172.196
LoadBalancer Ingress:     10.240.0.7
Port:                     <unset>  80/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30953/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age               From                Message
  ----    ------                ----              ----                -------
  Normal  EnsuringLoadBalancer  7s (x2 over 45m)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   7s (x2 over 44m)  service-controller  Ensured load balancer
```

4) Cannot curl from Azure cloud console to the external IP:
```bash
$ curl http://10.240.0.7
curl: (7) Failed to connect to 10.240.0.7 port 80: No route to host
```

If the set up the proxy through kubectl, I'm able to curl to the API:
```bash
$ kubectl port-forward -n presidio $(kubectl get pod -n presidio -l app=presidio-demo-presidio-api -o jsonpath='{.items[0].metadata.name}') 8080:8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080

$ curl localhost:8080
404 page not found
```

**Expected behavior**
```bash
curl http://10.240.0.7 should work from the cloud shell.
```
