### ISSUE TITLE
YAML regex does not work.

### ISSUE THREAD

**Issue by mirfan899** [microsoft/presidio#923]
**Describe the bug**
I'm trying to find the medical id from the string with the YAML file but it seems the regex is not working.
Here is my `YAML` file.

```yaml
recognizers:
  -
    name: "Medical ID recognizer"
    supported_language: "en"
    patterns:
      -
        name: "Medical ID"
        regex: r"\b\d{3}(-)\d{2}(-)\d{4}(A|B[1-7]?|M|T|C[1-4]|D)\b"
        score: 0.7
    context:
      - medical
      - id
    supported_entity: "MEDICAL_ID"
```

script to test it.

```python
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry, Pattern, PatternRecognizer

yaml_file = "my_recognizers/medical_id.yaml"
registry = RecognizerRegistry()
registry.add_recognizers_from_yaml(yaml_file)
analyzer = AnalyzerEngine(registry=registry)
result = analyzer.analyze(text="this is a medical id 315-77-8771, A 002-51-3788B2", language="en")
print(result)
```
returns empty array.

But when using a recognizer with python script it works.

```python
# Define the regex pattern
regex = r"\b\d{3}(-)\d{2}(-)\d{4}(A|B[1-7]?|M|T|C[1-4]|D)\b"
medical_pattern = Pattern(name="Medical ID pattern", regex=regex, score=0.5)
medical_recognizer = PatternRecognizer(supported_entity="MEDICAL_ID", patterns=[medical_pattern], context=["id", "medical"])
registry = RecognizerRegistry()
registry.add_recognizer(medical_recognizer)
analyzer = AnalyzerEngine(registry=registry)

results = analyzer.analyze(text="this is 315-77-8771 A 002-51-3788B2", language="en")
print(f"Result:\n {results}")
```
**To Reproduce**
1. load yaml recognizer
2. Use the text to recognize medical id(this is a medical id 315-77-8771, A 002-51-3788B2)
3. returns empty array instead of MEDICAL_ID
4. Run python snipper for the recognizer.
5. Gives medical id correctly.

**Expected behavior**
Yaml regex recognizer should work like the python snippet recognizer.

**Screenshots**
![regex_yaml](https://user-images.githubusercontent.com/3822565/192095026-ffff3a59-e805-4394-b0f9-a96f31c511d4.png)

**Additional context**
Nope

**Comment by ducquangkstn** [comment]
`r"\b\d{3}(-)\d{2}(-)\d{4}(A|B[1-7]?|M|T|C[1-4]|D)\b"` is not a valid YAML (it is not escaped as python)

You can test it at https://yaml-online-parser.appspot.com/

**Comment by mirfan899** [comment]
No error is shown on https://yaml-online-parser.appspot.com/ using the same regex.

The issue is most likely related to reading YAML regex.

It seems regex with `\b` will not work.
removing `\b` worked for me. Also regex starting with `r"regex here"` will not work in yaml file.

Here is a working example of same regex without `\b` character.

```yaml
recognizers:
  -
    name: "Medical ID recognizer"
    patterns:
      -
        name: "Medical ID"
        regex: "\\d{3}(-)\\d{2}(-)\\d{4}(A|B[1-7]?|M|T|C[1-4]|D)"
        score: 0.5
    context:
      - medical
      - id
    supported_entity: "MEDICAL_ID"
    supported_language: "en"
```

**Comment by omri374** [comment]
Hi @mirfan899, I can't seem to reproduce your issue.
Here is the code I tried:
```python
this_path = Path(__file__).parent.absolute()
test_yaml = Path(this_path, "conf/regex_recognizer_test.yaml")

registry = RecognizerRegistry()
registry.add_recognizers_from_yaml(test_yaml)
analyzer = AnalyzerEngine(registry=registry)
result = analyzer.analyze(text="this is a medical id 315-77-8771, A 002-51-3788B2", language="en")
print(result)
```

And the output I get:
```
[type: MEDICAL_ID, start: 36, end: 49, score: 0.85]
```

Could you validate that the recognizer is loaded correctly?
```python
registry = RecognizerRegistry()
registry.add_recognizers_from_yaml(test_yaml)
print(registry.recognizers[0])
```

**Comment by omri374** [comment]
On your first snippet, the regex in the yaml isn't in quotes. Could that be the issue?

**Comment by omri374** [comment]
This YAML would work:
```
recognizers:
  -
    name: "Medical ID recognizer"
    supported_language: "en"
    patterns:
      -
        name: "Medical ID"
        regex: '\b\d{3}(-)\d{2}(-)\d{4}(A|B[1-7]?|M|T|C[1-4]|D)\b'
        score: 0.7
    context:
      - medical
      - id
    supported_entity: "MEDICAL_ID"
```
